// SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie <jeff@ocjtech.us>
// SPDX-License-Identifier: MIT

//! Emits the case-folding tables `src/common.zig` matches with, from the
//! `CaseFolding.txt` that the `uucode` package vendors.
//!
//! Run by the build, never by hand; the output lands in the build cache and is
//! imported as the `casefold` module. Generating it means `uucode` is needed
//! only to build zregex, not to use it: what ships is the fifteen hundred
//! codepoints that actually fold, and nothing else.
//!
//! Only the `C` and `S` lines are read, which together are what Unicode calls
//! simple case folding. `F` is full folding, where one codepoint folds to
//! several -- `ß` to `ss` -- which is not what caseless matching does in PCRE
//! or anywhere else. `T` is the Turkic mapping, correct only for Turkish and
//! Azeri locales; reading it would make `İ` (U+0130) fold to `i`, and PCRE
//! matches `İ` against neither `i` nor `I`.
//!
//! Two tables come out of it, because matching wants two different things:
//!
//!   * `folds` answers "what does this codepoint fold to", which is what a
//!     backreference needs -- the text it compares against is only known while
//!     matching, so nothing about it can be folded ahead of time.
//!
//!   * `orbits` groups codepoints that fold alike. A caseless literal or class
//!     is rewritten into the union of its members' orbits while the pattern is
//!     compiled, so case folding disappears before matching starts and every
//!     engine, the JIT and the prefilter included, sees an ordinary class.
const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len < 3) {
        std.debug.print("usage: gen_casefold <CaseFolding.txt> <output.zig>\n", .{});
        std.process.exit(2);
    }

    const text = try std.Io.Dir.cwd().readFileAlloc(init.io, args[1], gpa, .limited(8 << 20));
    defer gpa.free(text);

    // Every codepoint that folds to something other than itself, in order.
    var folds: std.ArrayList([2]u21) = .empty;
    defer folds.deinit(gpa);
    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |raw| {
        // `CODE; STATUS; MAPPING; # NAME`, with `#` starting a comment.
        const line = std.mem.trimStart(u8, raw[0 .. std.mem.indexOfScalar(u8, raw, '#') orelse raw.len], " ");
        if (line.len == 0) continue;
        var parts = std.mem.splitScalar(u8, line, ';');
        const code = std.mem.trim(u8, parts.next() orelse continue, " ");
        const status = std.mem.trim(u8, parts.next() orelse continue, " ");
        const mapping = std.mem.trim(u8, parts.next() orelse continue, " ");
        // Simple case folding is `C` and `S` only; see the note above.
        if (status.len != 1 or (status[0] != 'C' and status[0] != 'S')) continue;
        const from = std.fmt.parseInt(u21, code, 16) catch continue;
        // A `C` or `S` mapping is always a single codepoint.
        if (std.mem.indexOfScalar(u8, mapping, ' ') != null) continue;
        const to = std.fmt.parseInt(u21, mapping, 16) catch continue;
        if (from != to) try folds.append(gpa, .{ from, to });
    }
    // The file is in code order already, but nothing promises it, and the
    // lookup in `common.zig` is a binary search.
    std.mem.sort([2]u21, folds.items, {}, struct {
        fn lt(_: void, a: [2]u21, b: [2]u21) bool {
            return a[0] < b[0];
        }
    }.lt);

    // Group them by what they fold to. A group plus its fold target is one
    // case-equivalence class: every member matches every other under `(?i)`.
    var groups: std.AutoArrayHashMapUnmanaged(u21, std.ArrayList(u21)) = .empty;
    defer {
        for (groups.values()) |*v| v.deinit(gpa);
        groups.deinit(gpa);
    }
    for (folds.items) |pair| {
        const slot = try groups.getOrPut(gpa, pair[1]);
        if (!slot.found_existing) {
            slot.value_ptr.* = .empty;
            // The target is a member of its own class.
            try slot.value_ptr.append(gpa, pair[1]);
        }
        try slot.value_ptr.append(gpa, pair[0]);
    }

    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(gpa);
    const w = &out;

    try w.appendSlice(gpa,
        \\// SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie <jeff@ocjtech.us>
        \\// SPDX-License-Identifier: MIT
        \\
        \\//! Generated by tools/gen_casefold.zig from CaseFolding.txt.
        \\//! Do not edit; change the generator instead.
        \\
        \\/// Codepoints whose simple case folding is not themselves, paired with
        \\/// what they fold to, sorted by the first element so a binary search
        \\/// finds one.
        \\pub const folds = [_][2]u21{
        \\
    );
    for (folds.items) |pair| {
        try w.print(gpa, "    .{{ 0x{x}, 0x{x} }},\n", .{ pair[0], pair[1] });
    }
    try w.appendSlice(gpa,
        \\};
        \\
        \\/// Case-equivalence classes holding more than one codepoint, each
        \\/// sorted. A codepoint absent from every one of these is equivalent
        \\/// only to itself, which is nearly all of them.
        \\pub const orbits = [_][]const u21{
        \\
    );

    // Sorted by first member, so the generated file is stable across runs and
    // a reader can find a codepoint in it.
    const keys = try gpa.dupe(u21, groups.keys());
    defer gpa.free(keys);
    for (groups.values()) |*v| std.mem.sort(u21, v.items, {}, std.sort.asc(u21));
    std.mem.sort(u21, keys, groups, struct {
        fn lt(g: @TypeOf(groups), a: u21, b: u21) bool {
            return g.get(a).?.items[0] < g.get(b).?.items[0];
        }
    }.lt);

    for (keys) |key| {
        const members = groups.get(key).?.items;
        try w.appendSlice(gpa, "    &.{");
        for (members, 0..) |mcp, i| {
            if (i != 0) try w.appendSlice(gpa, ",");
            try w.print(gpa, " 0x{x}", .{mcp});
        }
        try w.appendSlice(gpa, " },\n");
    }
    try w.appendSlice(gpa, "};\n");

    var file = try std.Io.Dir.cwd().createFile(init.io, args[2], .{});
    defer file.close(init.io);
    var buf: [4096]u8 = undefined;
    var fw = file.writer(init.io, &buf);
    try fw.interface.writeAll(out.items);
    try fw.interface.flush();
}
